#
#	start_warnings
#	no bootproto set. Defaulting to DHCP.
#	end_warnings
#
include ./scriptedinstall/commands/possitive.vmaccepteula.bs
include ./scriptedinstall/commands/possitive.rootpw.plaintext.bs
include ./scriptedinstall/commands/possitive.clearpart.minimal.bs
include ./scriptedinstall/commands/possitive.partition.minimal.bs
include ./scriptedinstall/commands/possitive.network.noBootproto.bs
include ./scriptedinstall/commands/possitive.auth.enableNIS.bs
