#
#	start_errors
#	A '/' (root) partition was not specified for the Service Console virtual disk.  The Service Console can not boot without a '/' partition.
#	end_errors
include ./scriptedinstall/commands/possitive.vmaccepteula.bs
include ./scriptedinstall/commands/possitive.rootpw.plaintext.bs
include ./scriptedinstall/commands/possitive.network.bootproto.dhcp.bs
include ./scriptedinstall/commands/possitive.clearpart.minimal.bs
include ./scriptedinstall/commands/negative.partition.noRoot.bs
include ./scriptedinstall/commands/possitive.auth.enableNIS.bs
