#
#	start_errors
#	mount point already exists.
#	end_errors
include ./scriptedinstall/commands/possitive.vmaccepteula.bs
include ./scriptedinstall/commands/possitive.rootpw.plaintext.bs
include ./scriptedinstall/commands/possitive.network.bootproto.dhcp.bs
include ./scriptedinstall/commands/possitive.auth.enableNIS.bs
include ./scriptedinstall/commands/possitive.esxlocation.firstdisk.bs
include ./scriptedinstall/commands/possitive.partition.minimal.bs
