# mode: -*- doctest -*-

clearpart --drives=vml.0000 --overwritevmfs
autopart --drive=vml.0000
vmaccepteula
rootpw mypassword
network --bootproto=dhcp --device=vmnic32
auth --enablemd5 --enableshadow --enablead --addomain=foo --addc=10.20.11.1

install cdrom

reboot

>>> import docage
>>> docage.run()
>>> import fauxroot
>>> "install depot is /mnt/source" in fauxroot.WRITTEN_FILES['/var/log/weasel.log'].getvalue()
True
>>> "installation aborted" not in fauxroot.WRITTEN_FILES['/var/log/weasel.log'].getvalue()
True
>>> "installation complete" in fauxroot.WRITTEN_FILES['/var/log/weasel.log'].getvalue()
True
>>> docage.printSystemLog()
['chvt', '6']
['/bin/bash', '/tmp/initscripts.sh']
['cd', '/', '&&', 'INSTALLER=1', '/init', '14.foobar']
['cd', '/', '&&', 'INSTALLER=1', '/init', '71.bogusipmi']
['echo', 'mkblkdevs', '|', 'nash', '--force']
['touch', '/etc/ntp.conf']
['echo', 'mkblkdevs', '|', 'nash', '--force']
['/usr/sbin/mkfs.ext2', '/dev/sda1']
['touch', '/etc/mtab']
['/usr/sbin/tune2fs', '-c0', '-i0', '-j', '/dev/sda1']
['/usr/sbin/vmkfstools', '-C', 'vmfs3', '-b', '1m', '-S', 'datastore1', '/vmfs/devices/disks/vml.0000:4']
['/usr/sbin/vmkfstools', '-c', '7604M', '/vmfs/volumes/datastore1/esxconsole-47b51b25-7c15-28d3-7cd0-000c2935404a/esxconsole.vmdk']
['/usr/sbin/vsd', '-cu', '-f', '/vmfs/volumes/datastore1/esxconsole-47b51b25-7c15-28d3-7cd0-000c2935404a/esxconsole.vmdk']
['echo', 'mkblkdevs', '|', 'nash', '--force']
['echo', 'mkblkdevs', '|', 'nash', '--force']
['/usr/sbin/mkswap', '-v1', '/dev/sdh1']
['/usr/sbin/mkfs.ext2', '/dev/sdh2']
['touch', '/etc/mtab']
['/usr/sbin/tune2fs', '-c0', '-i0', '-j', '/dev/sdh2']
['/usr/sbin/mkfs.ext2', '-L', 'esx-root', '/dev/sdh4']
['touch', '/etc/mtab']
['/usr/sbin/tune2fs', '-c0', '-i0', '-j', '/dev/sdh4']
['/usr/bin/mount', '/dev/sdh4', '/mnt/sysimage']
['/usr/bin/mount', '/dev/sda1', '/mnt/sysimage/boot']
['/usr/bin/mount', '/dev/sdh2', '/mnt/sysimage/var/log']
['/usr/bin/mount', '-t', 'proc', '/proc', '/mnt/sysimage//proc']
['/usr/bin/mount', '-t', 'sysfs', '/sys', '/mnt/sysimage//sys']
['/bin/rpm', '--rebuilddb']
['/sbin/chkconfig', 'netfs', 'off']
['/sbin/chkconfig', 'nfslock', 'off']
['/sbin/chkconfig', 'portmap', 'off']
['/sbin/chkconfig', 'iptables', 'off']
['/sbin/chkconfig', 'sshd', 'on']
['/usr/sbin/esxupdate', 'syncdb', '-m', '/tmp/metadata.zip']
['/mnt/sysimage/usr/sbin/esxcfg-configcheck']
['/usr/sbin/esxcfg-auth', '--kickstart', '--nostart', '--usepamqc', '8', '8', '8', '7', '6', '0', '--disablenis', '--disableldap', '--disableldapauth', '--disableldaptls', '--disablekrb5']
['/usr/bin/chage', '-M', '-1', 'root']
['touch', '/mnt/sysimage//etc/vmware/sysboot.conf']
['/usr/sbin/esxcfg-boot', '-b', '--update-trouble']
['/usr/sbin/grub', '--batch', '--device-map=/tmp/device.map', '<<EOF', 'root', '(hd0,0)', 'setup', '(hd0)', 'quit', 'EOF']
['/usr/sbin/esxcfg-boot', '--rebuild', '-b', '--update-trouble']
['/usr/bin/eject', '/dev/cdrom']
['/etc/init.d/iptables', 'stop']
['/usr/bin/umount', '/mnt/sysimage/proc']
['/usr/bin/umount', '/mnt/sysimage/sys']
['/usr/bin/umount', '/mnt/sysimage/var/log']
['/usr/bin/umount', '/mnt/sysimage/boot']
['/usr/bin/umount', '/mnt/sysimage']
['/usr/bin/umount', '/mnt/source']
['/usr/bin/eject']
>>> docage.printFiles(["/mnt/sysimage/root/ks.cfg"])
/mnt/sysimage/root/ks.cfg (unmounted f 600)
<BLANKLINE>
  reboot
  accepteula
<BLANKLINE>
  keyboard us
<BLANKLINE>
  auth
<BLANKLINE>
  # Canonical drive names:
  clearpart --drives=vml.0000
  # Uncomment to use first detected disk:
  #clearpart --firstdisk
<BLANKLINE>
  # Uncomment the esxlocation line and comment out the clearpart
  # and physical partitions to do a non-destructive reinstall.
  #esxlocation --uuid=4aa8e7c6-24ef-4f3e-9986-e628f7d1d51b
<BLANKLINE>
  install cdrom
<BLANKLINE>
  rootpw --iscrypted ...
<BLANKLINE>
  network --addvmportgroup=true --device=vmnic32 --bootproto=dhcp
<BLANKLINE>
  part '/boot'  --fstype=ext3 --size=1100  --ondisk=vml.0000
  # Uncomment to use first detected disk:
  #part '/boot'  --fstype=ext3 --size=1100  --onfirstdisk
  part 'none'  --fstype=vmkcore --size=110  --ondisk=vml.0000
  # Uncomment to use first detected disk:
  #part 'none'  --fstype=vmkcore --size=110  --onfirstdisk
  part 'datastore1'  --fstype=vmfs3 --size=8604 --grow  --ondisk=vml.0000
  # Uncomment to use first detected disk:
  #part 'Storage1'  --fstype=vmfs3 --size=8604 --grow  --onfirstdisk
<BLANKLINE>
  virtualdisk 'esxconsole' --size=7604 --onvmfs='datastore1'
<BLANKLINE>
  part 'swap'  --fstype=swap --size=600 --onvirtualdisk='esxconsole'
  part '/var/log'  --fstype=ext3 --size=2000 --onvirtualdisk='esxconsole'
  part '/'  --fstype=ext3 --size=5000 --grow --onvirtualdisk='esxconsole'
<BLANKLINE>
  %post --interpreter=bash
<BLANKLINE>
