# mode: -*- doctest -*-

vmaccepteula
rootpw mypassword
network --bootproto=dhcp --device=vmnic32
auth --enablemd5 --enableshadow

esxlocation --firstdisk

virtualdisk esxconsole --size=6000 --onfirstvmfs

part / --size=3500 --grow --onvirtualdisk=esxconsole --fstype=ext3
part /var/log --size=500 --grow --onvirtualdisk=esxconsole --fstype=ext3
part /var --size=200 --grow --onvirtualdisk=esxconsole --fstype=ext3
part swap --size=256 --onvirtualdisk=esxconsole --fstype=swap

install cdrom

reboot

>>> import docage
>>> import fauxroot
>>> docage.run()
>>> # print docage.newStdout.getvalue()
>>> "installation aborted" not in fauxroot.WRITTEN_FILES['/var/log/weasel.log'].getvalue()
True
>>> "installation complete" in fauxroot.WRITTEN_FILES['/var/log/weasel.log'].getvalue()
True
>>> docage.printSystemLog()
['chvt', '6']
['/bin/bash', '/tmp/initscripts.sh']
['cd', '/', '&&', 'INSTALLER=1', '/init', '14.foobar']
['cd', '/', '&&', 'INSTALLER=1', '/init', '71.bogusipmi']
['echo', 'mkblkdevs', '|', 'nash', '--force']
['touch', '/etc/ntp.conf']
['/usr/sbin/vmkfstools', '-c', '6000M', '/vmfs/volumes/Storage1/esxconsole-47b51b25-7c15-28d3-7cd0-000c2935404a/esxconsole.vmdk']
['/usr/sbin/vsd', '-cu', '-f', '/vmfs/volumes/Storage1/esxconsole-47b51b25-7c15-28d3-7cd0-000c2935404a/esxconsole.vmdk']
['echo', 'mkblkdevs', '|', 'nash', '--force']
['echo', 'mkblkdevs', '|', 'nash', '--force']
['/usr/sbin/mkswap', '-v1', '/dev/sdh1']
['/usr/sbin/mkfs.ext2', '-L', 'esx-root', '/dev/sdh2']
['touch', '/etc/mtab']
['/usr/sbin/tune2fs', '-c0', '-i0', '-j', '/dev/sdh2']
['/usr/sbin/mkfs.ext2', '/dev/sdh4']
['touch', '/etc/mtab']
['/usr/sbin/tune2fs', '-c0', '-i0', '-j', '/dev/sdh4']
['/usr/sbin/mkfs.ext2', '/dev/sdh5']
['touch', '/etc/mtab']
['/usr/sbin/tune2fs', '-c0', '-i0', '-j', '/dev/sdh5']
['/usr/bin/mount', '/dev/sdh2', '/mnt/sysimage']
['/usr/bin/mount', '/dev/sda1', '/mnt/sysimage/boot']
['/usr/bin/mount', '/dev/sdh5', '/mnt/sysimage/var']
['/usr/bin/mount', '/dev/sdh4', '/mnt/sysimage/var/log']
['/usr/bin/mount', '-t', 'proc', '/proc', '/mnt/sysimage//proc']
['/usr/bin/mount', '-t', 'sysfs', '/sys', '/mnt/sysimage//sys']
['/bin/rpm', '--rebuilddb']
['/sbin/chkconfig', 'netfs', 'off']
['/sbin/chkconfig', 'nfslock', 'off']
['/sbin/chkconfig', 'portmap', 'off']
['/sbin/chkconfig', 'iptables', 'off']
['/sbin/chkconfig', 'sshd', 'on']
['/usr/sbin/esxupdate', 'syncdb', '-m', '/tmp/metadata.zip']
['/mnt/sysimage/usr/sbin/esxcfg-configcheck']
['/usr/sbin/esxcfg-auth', '--kickstart', '--nostart', '--usepamqc', '8', '8', '8', '7', '6', '0', '--disablenis', '--disableldap', '--disableldapauth', '--disableldaptls', '--disablekrb5']
['/usr/bin/chage', '-M', '-1', 'root']
['touch', '/mnt/sysimage//etc/vmware/sysboot.conf']
['/usr/sbin/esxcfg-boot', '-b', '--update-trouble']
['/usr/sbin/grub', '--batch', '--device-map=/tmp/device.map', '<<EOF', 'root', '(hd0,0)', 'setup', '(hd0)', 'quit', 'EOF']
['/usr/sbin/esxcfg-boot', '--rebuild', '-b', '--update-trouble']
['/usr/bin/eject', '/dev/cdrom']
['/etc/init.d/iptables', 'stop']
['/usr/bin/umount', '/mnt/sysimage/proc']
['/usr/bin/umount', '/mnt/sysimage/sys']
['/usr/bin/umount', '/mnt/sysimage/var/log']
['/usr/bin/umount', '/mnt/sysimage/var']
['/usr/bin/umount', '/mnt/sysimage/boot']
['/usr/bin/umount', '/mnt/sysimage']
['/usr/bin/umount', '/mnt/source']
['/usr/bin/eject']
>>> docage.printPartitions()
/dev/sdn PARTITIONS:
[{'num': 0, 'fs_type': {'formattable': True, 'name': 'ext3'}, 'flags': {}, 'native_type': 131, 'geom': {'start': 0, 'end': 100}, 'type': 0}]
/dev/sdt PARTITIONS:
[]
/dev/sdq PARTITIONS:
[]
/dev/cciss/c0d1 PARTITIONS:
[]
/dev/cciss/c0d0 PARTITIONS:
[]
/dev/sdm PARTITIONS:
[]
/dev/sdh PARTITIONS:
[{'num': 1, 'fs_type': {'formattable': True, 'name': 'linux-swap'}, 'flags': {}, 'native_type': 130, 'geom': {'start': 0L, 'end': 524287.0}, 'type': 0},
 {'num': 2, 'fs_type': {'formattable': True, 'name': 'ext3'}, 'flags': {}, 'native_type': 131, 'geom': {'start': 524288.0, 'end': 2097501524.0}, 'type': 0},
 {'num': 3, 'fs_type': None, 'flags': {}, 'native_type': None, 'geom': {'start': 2097501525.0, 'end': 6291455999L}, 'type': 2},
 {'num': 4, 'fs_type': {'formattable': True, 'name': 'ext3'}, 'flags': {}, 'native_type': 131, 'geom': {'start': 2097501525.0, 'end': 4194478761.0}, 'type': 1},
 {'num': 5, 'fs_type': {'formattable': True, 'name': 'ext3'}, 'flags': {}, 'native_type': 131, 'geom': {'start': 4194478762.0, 'end': 6291455999.0}, 'type': 1}]
/dev/sdf PARTITIONS:
[{'num': 0, 'fs_type': {'formattable': True, 'name': 'ext3'}, 'flags': {}, 'native_type': 131, 'geom': {'start': 0, 'end': 200}, 'type': 0},
 {'num': 1, 'fs_type': {'formattable': True, 'name': 'ext3'}, 'flags': {}, 'native_type': 131, 'geom': {'start': 220, 'end': 600}, 'type': 0}]
/dev/sdg PARTITIONS:
[{'num': 0, 'fs_type': {'formattable': True, 'name': 'ext3'}, 'flags': {}, 'native_type': 131, 'geom': {'start': 0, 'end': 100}, 'type': 0}]
/dev/sdd PARTITIONS:
[{'num': 0, 'fs_type': {'formattable': True, 'name': 'ext3'}, 'flags': {}, 'native_type': 131, 'geom': {'start': 0, 'end': 100}, 'type': 0}]
/dev/sde PARTITIONS:
[]
/dev/sdb PARTITIONS:
[{'num': 5, 'fs_type': '', 'flags': {}, 'native_type': 251, 'geom': {'start': 100, 'end': 200}, 'type': 1}]
/dev/sda PARTITIONS:
[{'num': 0, 'fs_type': {'formattable': True, 'name': 'ext3'}, 'flags': {}, 'native_type': 131, 'geom': {'start': 0, 'end': 204800}, 'type': 0},
 {'num': 1, 'fs_type': {'formattable': True, 'name': 'ext3'}, 'flags': {}, 'native_type': 131, 'geom': {'start': 204820, 'end': 400000}, 'type': 0},
 {'num': 2, 'fs_type': '', 'flags': {}, 'native_type': 251, 'geom': {'start': 400020, 'end': 700000}, 'type': 0}]
>>> docage.printFiles(["/etc/ntp.conf",
...                    "/mnt/sysimage/etc/fstab",
...                    "/mnt/sysimage/boot/grub/grub.conf",
...                    "/mnt/sysimage/root/ks.cfg",
...                    "/mnt/sysimage/etc/sysconfig/keyboard",
...                    "/mnt/sysimage/etc/sysconfig/clock",
...                    "/mnt/sysimage/etc/sysconfig/i18n"])
/etc/ntp.conf (regular f 700)
/mnt/sysimage/boot/grub/grub.conf (unmounted f 600)
  default 0
  ###################### grub.conf #####################
  # this file was generated by bootloader.py
  #
  # Any entries in this file marked with the comment
  #   #vmware:autogenerated esx
  # Should not be edited by hand.  They are likely to
  # be clobbered on or before the next reboot.
  #
  timeout=5
<BLANKLINE>
  title ESX vmkernel
          #vmware:autogenerated esx
          root (hd0,0)
          uppermem 307200
          kernel /vmlinuz ro root=UUID=4aa8e7c6-24ef-4f3e-9986-e628f7d1d51f mem=300M quiet
          initrd /initrd.img
  title Troubleshooting mode
          #vmware:autogenerated esx
          root (hd0,0)
          uppermem 307200
          kernel /trouble/vmlinuz ro root=UUID=4aa8e7c6-24ef-4f3e-9986-e628f7d1d51f mem=300M trouble quiet
          initrd /trouble/initrd.img
<BLANKLINE>
/mnt/sysimage/etc/fstab (unmounted f 700)
  UUID=4aa8e7c6-24ef-4f3e-9986-e628f7d1d51f /                       ext3    defaults        1 1
  UUID=4aa8e7c6-24ef-4f3e-9986-e628f7d1d51b /boot                   ext3    defaults        1 2
  None                    /dev/pts                devpts  defaults        0 0
  /dev/cdrom              /mnt/cdrom              udf,iso9660 noauto,owner,kudzu,ro 0 0
  /dev/fd0                /mnt/floppy             auto    noauto,owner,kudzu 0 0
  None                    /proc                   proc    defaults        0 0
  None                    /sys                    sysfs   defaults        0 0
  UUID=4aa8e7c6-24ef-4f3e-9986-e628f7d1d51d /var                    ext3    defaults        1 2
  UUID=4aa8e7c6-24ef-4f3e-9986-e628f7d1d51c /var/log                ext3    defaults,errors=panic 1 2
  UUID=4aa8e7c6-24ef-4f3e-9986-000000000001 swap                    swap    defaults        0 0
<BLANKLINE>
/mnt/sysimage/etc/sysconfig/clock (unmounted f 700)
  ZONE=US/Pacific
  UTC=true
  ARC=false
<BLANKLINE>
/mnt/sysimage/etc/sysconfig/i18n (unmounted f 700)
  LANG="en_US.UTF-8"
<BLANKLINE>
/mnt/sysimage/etc/sysconfig/keyboard (unmounted f 700)
  KEYTABLE="us"
  KEYBOARDTYPE="pc"
<BLANKLINE>
/mnt/sysimage/root/ks.cfg (unmounted f 600)
<BLANKLINE>
  reboot
  accepteula
<BLANKLINE>
  keyboard us
<BLANKLINE>
  auth 
<BLANKLINE>
  esxlocation --uuid=4aa8e7c6-24ef-4f3e-9986-e628f7d1d51b
<BLANKLINE>
  install cdrom
<BLANKLINE>
  rootpw --iscrypted ...
<BLANKLINE>
  network --addvmportgroup=true --device=vmnic32 --bootproto=dhcp
<BLANKLINE>
  virtualdisk 'esxconsole' --size=6000 --onvmfs='Storage1'
<BLANKLINE>
  part 'swap'  --fstype=swap --size=256 --onvirtualdisk='esxconsole'
  part '/'  --fstype=ext3 --size=3500 --grow --onvirtualdisk='esxconsole'
  part '/var/log'  --fstype=ext3 --size=500 --grow --onvirtualdisk='esxconsole'
  part '/var'  --fstype=ext3 --size=200 --grow --onvirtualdisk='esxconsole'
<BLANKLINE>
  %post --interpreter=bash
<BLANKLINE>
