#
#	start_warnings
#	--disablemd5 is deprecated
#	--disableshadow is deprecated
#	end_warnings
#	start_verify
#	userchoices.getAuth()['nis'] == False
#	userchoices.getAuth()['kerberos'] == False
#	userchoices.getAuth()['ldap'] == True
#	userchoices.getAuth()['ldapAuth'] == True
#	userchoices.getAuth()['ldapServer'] == ''
#	userchoices.getAuth()['ldapBaseDN'] == ''
#	userchoices.getAuth()['ldapTLS'] == False
#	end_verify
include ./scriptedinstall/files/possitive.minimal.warn.bs
include ./scriptedinstall/commands/possitive.auth.enableLDAPAuth.bs
