#
#	start_warnings
#	--disableshadow is deprecated
#	--enablemd5 is deprecated
#	end_warnings
#	start_verify
#	userchoices.getRootPassword()['password'] != 'mypassword'
#	userchoices.getRootPassword()['passwordType'] == userchoices.ROOTPASSWORD_TYPE_MD5
#	end_verify
include ./scriptedinstall/commands/possitive.vmaccepteula.bs
include ./scriptedinstall/commands/possitive.auth.enableMD5.bs
include ./scriptedinstall/commands/possitive.rootpw.plaintext.bs
include ./scriptedinstall/commands/possitive.clearpart.minimal.bs
include ./scriptedinstall/commands/possitive.partition.minimal.bs
include ./scriptedinstall/commands/possitive.network.bootproto.dhcp.bs
